# Generated by Django 2.2.2 on 2020-12-21 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUsers',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(default='', max_length=250, null=True)),
                ('username', models.CharField(default='', max_length=250, null=True)),
                ('useremail', models.CharField(default='', max_length=250, null=True)),
                ('password', models.CharField(default='', max_length=250, null=True)),
                ('status', models.CharField(default='active', max_length=50, null=True)),
                ('user_created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authenticated_users',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(default='', max_length=100, null=True)),
                ('blog_content', models.TextField(default='', max_length=2500, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(default='', max_length=100, null=True)),
                ('author_usercode', models.CharField(default='', max_length=100, null=True)),
                ('author_email', models.CharField(default='', max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='BlogReader',
            fields=[
                ('reader_id', models.AutoField(primary_key=True, serialize=False)),
                ('reader_name', models.CharField(default='', max_length=100, null=True)),
                ('reader_usercode', models.CharField(default='', max_length=100, null=True)),
                ('reader_email', models.CharField(default='', max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reader',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=100, null=True)),
                ('role_code', models.CharField(default='', max_length=50, null=True)),
                ('role_status', models.CharField(default='', max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_or_not', models.BooleanField()),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogReader')),
            ],
            options={
                'db_table': 'response',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(default='', max_length=2500, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogReader')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogAuthor'),
        ),
    ]
