# Generated by Django 2.2.2 on 2020-12-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authusers',
            name='role_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blogs.Role'),
        ),
    ]
