# Generated by Django 2.2.2 on 2020-12-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201221_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modified_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
