# Generated by Django 2.2.2 on 2020-12-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201221_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='c_time',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='m_time',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
