# Generated by Django 2.2.2 on 2020-12-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201221_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='c_time',
        ),
        migrations.AlterField(
            model_name='blog',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
