# Generated by Django 2.2.2 on 2020-12-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20201221_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
