# Generated by Django 2.2.2 on 2020-12-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20201221_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='count_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='count_likes',
            field=models.IntegerField(default=0),
        ),
    ]
