# Generated by Django 2.2.2 on 2020-12-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20201221_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='m_time',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
