# Generated by Django 2.2.2 on 2020-12-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20201222_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='count_comments',
            field=models.IntegerField(default=0),
        ),
    ]
